rpc:
  host: 0.0.0.0
  token: ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW
governance:
  timeoutMillSeconds: 0  
registrycenter:
  connectionStrings: 192.168.99.100:2181
  type: Zookeeper
distributedCache:
  redis:
    isEnabled: true
    configuration: 192.168.99.100:6379,defaultDatabase=0
gateway:
  jwtSecret: jv1PZkwjLVCEygM7faLLvEhDGWmFqRUW
swaggerDocument:
  organizationMode: Group
  termsOfService: https://www.github.com/liuhll/silky

dashboard:
  displayWebApiInSwagger: false
  useAuth: true
  wrapperResponse: true
  dashboardLoginApi: /api/account/dashboard/login
  externalLinks:
    - title: "message.swagger"
      path: "http://localhost:5002"
      icon: "iconfont icon-swagger"
    - title: "SkyWalking"
      path: "http://localhost:8180"
    - title: "Github"
      path: "https://github.com/liuhll/silky"
      icon: "iconfont icon-github"
    - title: "Gitee"
      path: "https://gitee.com/liuhll2/silky"
      icon: "iconfont icon-gitee2"