rpc:
  host: 0.0.0.0
  port: 2201
  token: ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW
governance:
  timeoutMillSeconds: 0
registrycenter:
  connectionStrings: 192.168.99.100:2181
  type: Zookeeper
distributedCache:
  redis:
    isEnabled: true
    configuration: 192.168.99.100:6379,defaultDatabase=0
connectionStrings:
    default: server=127.0.0.1;port=3306;database=account;uid=root;pwd=root;
jwtSettings:
  secret: jv1PZkwjLVCEygM7faLLvEhDGWmFqRUW